name: solar_team_twente # This will be updated to solar_team_twente by Mason
version: 0.0.1

publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ^3.22.0

dependencies:
  accessibility_tools: ^2.0.0
  awesome_flutter_extensions: ^1.2.0
  cached_network_image: ^3.3.1
  camera: ^0.10.5+9
  dio: ^5.4.3+1
  dio_cache_interceptor: ^3.5.0
  dio_smart_retry: ^6.0.0
  equatable: ^2.0.5
  firebase_analytics: ^10.10.5
  firebase_core: ^2.31.0
  firebase_crashlytics: ^3.5.5
  firebase_messaging: ^14.9.2
  flag: ^7.0.0
  flex_seed_scheme: ^1.5.0
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.10+1
  flutter_bloc: ^8.1.5
  flutter_gutter: ^1.0.0
  flutter_ioc: ^2.1.0
  flutter_ioc_get_it: ^1.2.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_secure_storage: ^9.0.0
  flutter_web_plugins:
    sdk: flutter
  form_builder_validators: ^9.1.0
  go_router: ^14.0.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.9.0
  locale_names: ^1.1.1
  lottie: ^3.1.0
  material_symbols_icons: ^4.2719.3
  meta: ^1.11.0
  package_info_plus: ^8.0.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6

# Needs to override because some packages are not compatible with the latest version of intl
dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  retrofit_generator: ^8.1.0
  test: ^1.24.9
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/dark/
    - assets/light/
    - assets/animations/

flutter_gen:
  output: lib/src/assets/generated
