name: solar_team_twente
version: 1.1.1+8

publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ^3.24.0

dependencies:
  accessibility_tools: ^2.0.0
  awesome_flutter_extensions: ^1.2.0
  cached_network_image: ^3.4.0
  camera: ^0.11.0+1
  carousel_slider: ^5.0.0
  dio: ^5.4.3+1
  dio_cache_interceptor: ^3.5.0
  dio_smart_retry: ^6.0.0
  dotted_line: ^3.2.2
  equatable: ^2.0.5
  firebase_analytics: ^11.0.1
  firebase_core: ^3.1.0
  firebase_crashlytics: ^4.0.1
  firebase_messaging: ^15.0.1
  flag: ^7.0.0
  flex_seed_scheme: ^3.0.0
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.10+1
  flutter_bloc: ^8.1.5
  flutter_gutter: ^2.0.0
  flutter_ioc: ^2.1.0
  flutter_ioc_get_it: ^1.2.1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_map_animations: ^0.7.0
  flutter_map_cancellable_tile_provider: ^3.0.2
  flutter_map_geojson: ^1.0.8
  flutter_native_splash: ^2.4.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  flutter_web_plugins:
    sdk: flutter
  form_builder_validators: ^11.0.0
  go_router: ^14.0.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  locale_names: ^1.1.1
  lottie: ^3.1.0
  material_symbols_icons: ^4.2719.3
  meta: ^1.11.0
  package_info_plus: ^8.0.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  slide_countdown: ^1.6.1
  supabase_flutter: ^2.5.3
  url_launcher: ^6.2.6

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  retrofit_generator: ^8.1.0
  test: ^1.24.9
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/dark/
    - assets/light/
    - assets/animations/
    - assets/geojson/day_1.geojson
    - assets/geojson/day_2.geojson
    - assets/geojson/day_3.geojson
    - assets/geojson/day_4.geojson
    - assets/geojson/day_5.geojson
    - assets/geojson/day_6.geojson
    - assets/geojson/day_7.geojson
    - assets/geojson/day_8.geojson
    - assets/geojson/full_map.geojson
    - assets/icons/

flutter_gen:
  output: lib/src/assets/generated
