name: solar_team_twente
version: 1.1.1+8

publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ^3.32.0

dependencies:
  accessibility_tools: ^2.0.0
  cached_network_image: ^3.4.0
  carousel_slider: ^5.0.0
  dio: ^5.4.3+1
  dio_cache_interceptor: ^4.0.3
  dio_smart_retry: ^7.0.1
  dotted_line: ^3.2.2
  equatable: ^2.0.5
  firebase_analytics: ^11.0.1
  firebase_core: ^3.1.0
  firebase_crashlytics: ^4.0.1
  firebase_messaging: ^15.0.1
  flag: ^7.0.0
  flex_seed_scheme: ^3.0.0
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.3.3+1
  flutter_bloc: ^9.1.1
  flutter_gutter: ^2.2.0
  flutter_ioc: ^2.1.0
  flutter_ioc_get_it: ^1.2.1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.1.1
  flutter_map_animations: ^0.9.0
  flutter_map_cancellable_tile_provider: ^3.1.0
  flutter_map_geojson2: ^1.0.2
  flutter_native_splash: ^2.4.0
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_svg: ^2.0.10+1
  form_builder_validators: ^11.0.0
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  image_picker: ^1.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  locale_names: ^1.1.1
  lottie: ^3.1.0
  material_symbols_icons: ^4.2719.3
  meta: ^1.11.0
  package_info_plus: ^8.0.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  slide_countdown: ^2.0.2
  supabase_flutter: ^2.5.3
  url_launcher: ^6.2.6

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  retrofit_generator: ^9.2.0
  test: ^1.24.9
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/dark/
    - assets/light/
    - assets/animations/
    - assets/geojson/
    - assets/icons/

flutter_gen:
  output: lib/src/assets/generated
