// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGcM2nOWq_hfwxlD9iKkynXEgybNi6JJE',
    appId: '1:608162368906:web:1649b0fc7fd0666df78c73',
    messagingSenderId: '608162368906',
    projectId: 'flutter-base-app-dddee',
    authDomain: 'flutter-base-app-dddee.firebaseapp.com',
    storageBucket: 'flutter-base-app-dddee.appspot.com',
    measurementId: 'G-1XQX2HM0H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD57e4WCVHxMG9g-hzAd3Pj4rVqcW2zHdM',
    appId: '1:608162368906:android:14fd17f0b84141d0f78c73',
    messagingSenderId: '608162368906',
    projectId: 'flutter-base-app-dddee',
    storageBucket: 'flutter-base-app-dddee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcacHwKG84dF2jnb9ePgRZjOP_Gl6I8GY',
    appId: '1:608162368906:ios:d481fb6d7debd325f78c73',
    messagingSenderId: '608162368906',
    projectId: 'flutter-base-app-dddee',
    storageBucket: 'flutter-base-app-dddee.appspot.com',
    iosBundleId: 'com.baseflow.baseapp.dev',
  );

}