// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj8a_Xz23EAHAhxc5MCJJyQuI8DMHRZ8Q',
    appId: '1:639646983859:web:56cba5f0cb33fc6f9af2c6',
    messagingSenderId: '639646983859',
    projectId: 'solarteam-twente',
    authDomain: 'solarteam-twente.firebaseapp.com',
    storageBucket: 'solarteam-twente.appspot.com',
    measurementId: 'G-PX0Y065DR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJeuTol0sF1EqG7HuIHSis2YASbmuRGTk',
    appId: '1:639646983859:android:39770e2df2d64bc99af2c6',
    messagingSenderId: '639646983859',
    projectId: 'solarteam-twente',
    storageBucket: 'solarteam-twente.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0pCTMq44LeFLu7WblbbLw_Afn8w37MQE',
    appId: '1:639646983859:ios:b928a46b9c5df79f9af2c6',
    messagingSenderId: '639646983859',
    projectId: 'solarteam-twente',
    storageBucket: 'solarteam-twente.appspot.com',
    iosBundleId: 'com.baseflow.solarapp',
  );
}
